#!/usr/bin/env Rscript
library(GenomicRanges)
load("ensemble_construction_workplace.RData")

GEMSTAT_init_BOlinear(.exp.nu = 1,
                      .dir="/shared-mounts/sinhas/tabebor2/ER_Project/Model/GEMSTAT/based_on_linear",
                      .GEMSTAT_call = "/shared-mounts/sinhas/tabebor2/GEMSTAT_git/my_fork/GEMSTAT/src/seq2expr",
                      TF_names = names(TF.motifs.Shrinked.count),
                      model_evaluations = Sim_Ann_weighted_148_restart_all_models_eval,
                     # model_gene_ind = c(1,2),
                      model_parameters = Sim_Ann_weighted_148_restart_parameters
                      nu_enh_per_gene = 1,
                      TF_KD_evaluation = Sim_Ann_weighted_148_restart_TF_KD,
                      quantile_nu = 4,
                      enhancer_GRang = ER.associated.reg.elements_gte4nzKD_atl1p1n_52_seq_chopped_scoredPerPiece_filtered_perGene$Chopped_GRanges,
                      enhancer_Seq = ER.associated.reg.elements_gte4nzKD_atl1p1n_52_seq_chopped_scoredPerPiece_filtered_perGene$Chopped_Seq,
                      real_exp_mat = my_CommonDifExpMat_16_ERassoc_gte4nzKD_atl1p1n_52,
                      TF_expression_mat = TF.Exp.Shrinked.microarray_ENTREZ_PerDataset_unique_mat_dJun_ER01,
                      motif_list = TF.motifs.Shrinked.count,
                      annotation_thresh=numeric(0),
                      annotation_range=numeric(0),
                      initial_bind_w=numeric(0),
                      bind_w_range=numeric(0),
                      initial_alpha=numeric(0),
                      alpha_range=numeric(0),
                      coop_tf_mat=numeric(0),
                      initial_coop_weight=numeric(0),
                      coop_weight_range=numeric(0),
                      coop_type=character(0),
                      coop_dist=integer(0),
                      coop_orientation=integer(0),
                      .one_qbtm_per_enh=T,
                      initial_qBTM=numeric(0),
                      qBTMrange=numeric(0),
                      .one_beta_per_enh=T,
                      initial_pi_beta=numeric(0), 
                      pi_beta_upper=numeric(0),
                      pi_beta_lower=numeric(0),
                      annotation_thresh_ff=integer(0),
                      initial_bind_w_ff=integer(0),
                      initial_alpha_ff=integer(0),
                      initial_coop_weight_ff=integer(0),
                      initial_qBTM_ff=integer(0),
                      initial_pi_beta_ff=integer(0),
                      nu_enhacners = length(unlist(ER.associated.reg.elements_gte4nzKD_atl1p1n_52_seq_chopped_scoredPerPiece_filtered_perGene$Chopped_Seq)),
                      .ensemble_mode = F,
                      nu_samples = 0,
                      na = 2,
                      .job_file_name = "based_on_linear_1enh_perGene.job" 
                      #,annotation_thresh_ff_ens = annotation_thresh_ff,
                      #initial_coop_weight_ff_ens = initial_coop_weight_ff,
                     # initial_qBTM_ff_ens = initial_qBTM_ff
                      )